
const lessons = [
  {
    id: 101,
    subject: "Scrabble Tutorial",
    location: "Online",
    price: 890,
    spaces: 5,
    icon: "bi bi-spellcheck",
  },
  {
    id: 102,
    subject: "Desktop Tutorials",
    location: "Online",
    price: 43,
    spaces: 5,
    icon: "bi bi-pc-display-horizontal",
  },
  {
    id: 103,
    subject: "Baking Tutorial",
    location: "In Person",
    price: 98,
    spaces: 5,
    icon: "bi bi-cake2",
  },
  {
    id: 104,
    subject: 'Game Tutorial',
    location: "Online",
    price: 45.8,
    spaces: 5,
    icon: "bi bi-joystick",
  },
  {
    id: 105,
    subject: "Pilot Simulator",
    location: "In-Person",
    price: 89,
    spaces: 5,
    icon: "bi bi-airplane",
  },
  {
    id: 106,
    subject: "Library works",
    location: "In Person",
    price: 24,
    spaces: 5,
    icon: "bi bi-collection",
  },
  {
    id: 107,
    subject: "Chat Box",
    location: "Online",
    price: 32,
    spaces: 5,
    icon: "bi bi-chat-dots",
  },
  {
    id: 108,
    subject: "Car tutorial",
    location: "In Person",
    price: 87,
    spaces: 5,
    icon: "bi bi-car-front-fill",
  },
  {
    id: 109,
    subject: "Robotics",
    location: "In-Person",
    price: 50,
    spaces: 5,
    icon: "bi bi-android2",
  },
  {
    id: 110,
    subject: "Think and Grow Rich",
    location: "Book",
    price: 40,
    spaces: 5,
    icon: "bi bi-book-half",
  },
];

// module.exports = lessons;
